spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: coolpeace
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
# 1페이지부터 시작하려면 아래 설정 적용
#    web:
#      pageable:
#        one-indexed-parameters: true

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}