spring:

  config:
    import: optional:file:.env[.properties]
  application:
    name: coolpeace
  jackson:
    property-naming-strategy: SNAKE_CASE
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: dailyStatisticsJob

  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
    web:
      pageable:
        one-indexed-parameters: true

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
