spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: dailyStatisticsJob
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework.security: debug