spring:
  application:
    name: coolpeace-batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: dailyStatisticsJob

  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update