spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: coolpeace
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: true

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}