### 이전 쿠폰 등록 내역 불러오기
GET http://localhost:8080/v1/coupons/recent
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIyIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNvb2xwZWFjZSIsImlhdCI6MTcwNDQ1MTc5NiwiZXhwIjoxNzA0NDg3Nzk2fQ.LRqoTLb5TOz2q1F6VqiYEHXaU7PI32GBltomiJoKHEmT93YEdwjy9YdfQRtziadj6ZR_1gRKgqW26154b2oDxg
