### 이전 쿠폰 등록 내역 불러오기
GET http://localhost:8080/v1/coupons/recent
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIyIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNvb2xwZWFjZSIsImlhdCI6MTcwNDYzNzM1NSwiZXhwIjoxNzA0NjczMzU1fQ.EHA6wXVl3dpB26_QPdzGnZoBURKzUYf6d6-ciSPD9hw7iJy1rdzVEQUsXFI_72frPAf4DzvygLLv7Pxupm-g-Q
