### 쿠폰 등록
POST http://localhost:8080/v1/coupons/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIyIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNvb2xwZWFjZSIsImlhdCI6MTcwNDQ1MTc5NiwiZXhwIjoxNzA0NDg3Nzk2fQ.LRqoTLb5TOz2q1F6VqiYEHXaU7PI32GBltomiJoKHEmT93YEdwjy9YdfQRtziadj6ZR_1gRKgqW26154b2oDxg

{
  "title": "Title",
  "customer_type": "ALL_CLIENT",
  "discount_type": "FIXED_PRICE",
  "discount_value": 20,
  "coupon_room_type": "TWO_NIGHT",
  "accommodation_id": 1,
  "register_all_room": false,
  "register_rooms": [101, 102],
  "minimum_reservation_price": 0,
  "coupon_use_condition_days": ["MONDAY", "WEDNESDAY"],
  "exposure_start_date": "2023-04-01",
  "exposure_end_date": "2023-04-30"
}