### 쿠폰 검색
GET http://localhost:8080/v1/coupons?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIyIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNvb2xwZWFjZSIsImlhdCI6MTcwNDQ1MDE0NywiZXhwIjoxNzA0NDg2MTQ3fQ.jxa-S5-86JSTbiXXQHYnAjBMU6hUs0rS67Oh1siwfiyhtRFf4d_AUTsGUSkuYse0td_9btbqNP8Kyqjx2uPR6A
